<a href="https://colab.research.google.com/github/jeongukjae/edgetpu-detection/blob/main/load_mobilenet_edgetpu_v2_model_for_the_desired_resolution.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Load mobilenet-edgetpu-v2 l weight for the desired resolution

In [1]:
# Load TensorFlow/Models Repository
%%bash
git clone https://github.com/tensorflow/models.git
cd models
pip install -q -r official/requirements.txt

Cloning into 'models'...


In [2]:
import sys
sys.path.append("/content/models")
print(sys.path)

['', '/content', '/env/python', '/usr/lib/python37.zip', '/usr/lib/python3.7', '/usr/lib/python3.7/lib-dynload', '/usr/local/lib/python3.7/dist-packages', '/usr/lib/python3/dist-packages', '/usr/local/lib/python3.7/dist-packages/IPython/extensions', '/root/.ipython', '/content/models']


In [3]:
# Download mobilenet-edgetpu-v2-l
!curl -L -o mobilenet_edgetpu_v2_l.tar.gz https://tfhub.dev/google/edgetpu/vision/mobilenet-edgetpu-v2/l/1?tf-hub-format=compressed
!mkdir mobilenet_edgetpu_v2_l && tar -zxvf mobilenet_edgetpu_v2_l.tar.gz -C mobilenet_edgetpu_v2_l

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 39.4M  100 39.4M    0     0  34.6M      0  0:00:01  0:00:01 --:--:-- 46.9M
./
saved_model.pb
variables/
variables/variables.data-00000-of-00001
variables/variables.index


In [4]:
import tensorflow as tf
import tensorflow_hub as hub
from official.projects.edgetpu.vision.modeling import mobilenet_edgetpu_v2_model

In [5]:
# Set desired resolution
mobilenet_edgetpu_v2_model.MODEL_CONFIGS['mobilenet_edgetpu_v2_l'].resolution = 224

# Load model
model = tf.keras.Sequential([mobilenet_edgetpu_v2_model.MobilenetEdgeTPUV2('mobilenet_edgetpu_v2_l')])
model.load_weights('./mobilenet_edgetpu_v2_l')
saved_model = hub.KerasLayer("./mobilenet_edgetpu_v2_l")

input_tensor = tf.random.uniform((4, 224, 224, 3))

output_tensor_of_model = model(input_tensor)
output_tensor_of_saved_model = saved_model(input_tensor)

tf.debugging.assert_near(output_tensor_of_model, tf.reshape(output_tensor_of_saved_model, [4, -1]))

output_tensor_of_model, output_tensor_of_saved_model

(<tf.Tensor: shape=(4, 1001), dtype=float32, numpy=
 array([[9.2661001e-05, 2.9864634e-05, 4.5382878e-04, ..., 1.6427132e-04,
         2.6273497e-04, 1.2310965e-03],
        [1.3731039e-04, 3.7799557e-05, 5.6840648e-04, ..., 3.4786706e-04,
         3.9624702e-04, 2.9342361e-03],
        [1.1970452e-04, 3.3583328e-05, 5.0772633e-04, ..., 2.3009472e-04,
         3.4067195e-04, 1.5439325e-03],
        [1.0935631e-04, 3.5282996e-05, 5.5070460e-04, ..., 1.8341614e-04,
         2.4105274e-04, 1.5796019e-03]], dtype=float32)>,
 <tf.Tensor: shape=(4, 1, 1, 1001), dtype=float32, numpy=
 array([[[[9.26610228e-05, 2.98646410e-05, 4.53828688e-04, ...,
           1.64271449e-04, 2.62735179e-04, 1.23109564e-03]]],
 
 
        [[[1.37310373e-04, 3.77995348e-05, 5.68406074e-04, ...,
           3.47866997e-04, 3.96246993e-04, 2.93423468e-03]]],
 
 
        [[[1.19704651e-04, 3.35833502e-05, 5.07726683e-04, ...,
           2.30094767e-04, 3.40672181e-04, 1.54393190e-03]]],
 
 
        [[[1.09356464e-04,

In [6]:
# Load model for another resolution
mobilenet_edgetpu_v2_model.MODEL_CONFIGS['mobilenet_edgetpu_v2_l'].resolution = 640

# Load model
model = tf.keras.Sequential([mobilenet_edgetpu_v2_model.MobilenetEdgeTPUV2('mobilenet_edgetpu_v2_l')])
model.load_weights('./mobilenet_edgetpu_v2_l')

input_tensor = tf.random.uniform((4, 640, 640, 3))
output_tensor = model(input_tensor)

output_tensor

<tf.Tensor: shape=(4, 1001), dtype=float32, numpy=
array([[1.6194253e-04, 6.7916197e-05, 5.7522516e-04, ..., 2.5074702e-04,
        4.0254754e-04, 2.6845213e-03],
       [1.8369574e-04, 5.9758371e-05, 5.2225671e-04, ..., 3.3622628e-04,
        4.2625453e-04, 2.9568987e-03],
       [1.6727316e-04, 6.5213091e-05, 5.3526234e-04, ..., 2.7929756e-04,
        4.1795467e-04, 3.1115818e-03],
       [1.9033170e-04, 5.5491910e-05, 5.1072327e-04, ..., 3.6682148e-04,
        4.1839783e-04, 3.2259447e-03]], dtype=float32)>